TITLE SNAKE JUEGO DEL SNAKE 
.MODEL SMALL
.STACK 100H
.DATA
    BORDE DB 00010111B ; CIAN FONDO CHAR MAGENTA
    FONDO DB 01000111B ; CAFE EL AREA DE JUEGO
    SNAKE_COL DB 10 DUP(40)
    SNAKE_REN DB 22,9 DUP(23)
    SNAKE_CHAR DB 'O'
    SNAKE_LARGO DW 2
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    ; CAMBIAR EL MODO DE VIDEO
    MOV AH,0
    MOV AL,3
    INT 10H
    
    ; PONER PAGINA ACTIVA LA 0
    MOV AH,5
    MOV AL,0
    INT 10H
    
    
    CALL HACER_FIELD
    
    MOV CX,20
CICLO_PRINCIPAL:
    ;CALL HACER_FIELD
    CALL DESPLIEGA_SNAKE
    CALL ESPERA
    CALL BORRA_SNAKE
    CALL AVANZA_SNAKE
    LOOP CICLO_PRINCIPAL
    
    ; ESPERANDO CHAR
    MOV AH,1
    INT 21H
    
    
    
    MOV AH, 4CH
    INT 21H
MAIN ENDP

HACER_FIELD PROC
    PUSH CX
    ; HACER EL BORDE EXTERIOR, LIMPIANDO LA PANTALLA
    MOV AH, 6
    MOV AL,25
    MOV AX, 0600H 
    MOV CX, 0000H ; RENGLON CERO , COL 0
    MOV DX, 184FH ; RENGOL 18H, COL 4EH
    MOV BH, BORDE
    INT 10H 
    
    MOV AH,7
    MOV AL,0
    MOV CX,0101H
    MOV DX,174EH
    MOV BH,FONDO
    INT 10H
    POP CX
    RET
    
HACER_FIELD ENDP
DESPLIEGA_SNAKE PROC
    PUSH CX
    MOV CX, SNAKE_LARGO
    XOR SI, SI
    
MUESTRA_SNAKE:
    ; CAMBIAR A POSICION DE COL Y REN DE LA SNAKE
    MOV AH,2
    MOV DL,SNAKE_COL[SI]
    MOV DH,SNAKE_REN[SI]
    MOV BH,0
    INT 10H
    
    ; DESPLEGAR EL CHAR DEL SNAKE
    MOV AH,9
    MOV AL, SNAKE_CHAR
    MOV BH,0
    MOV BL,FONDO
    PUSH CX
    MOV CX,1
    INT 10H
    POP CX
    INC SI
    LOOP MUESTRA_SNAKE
    
    
    POP CX
    RET

DESPLIEGA_SNAKE ENDP

ESPERA PROC
    PUSH CX
    MOV CX, 0FFFFH
CICLO_ESPERA:
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    LOOP CICLO_ESPERA
    POP CX
    RET
    
ESPERA ENDP

AVANZA_SNAKE PROC
    PUSH CX
    MOV CX, SNAKE_LARGO
    XOR SI, SI
CICLO_AVANZA:
    DEC SNAKE_REN[SI]
    INC SI
    LOOP CICLO_AVANZA
    
    POP CX
    RET
AVANZA_SNAKE ENDP

BORRA_SNAKE PROC
    PUSH CX
    MOV CX, SNAKE_LARGO
    XOR SI, SI
    
    QUITA_SNAKE:
    ; CAMBIAR A POSICION DE COL Y REN DE LA SNAKE
    MOV AH,2
    MOV DL,SNAKE_COL[SI]
    MOV DH,SNAKE_REN[SI]
    MOV BH,0
    INT 10H
    
    ; DESPLEGAR EL CHAR DEL SNAKE
    MOV AH,9
    MOV AL, " "
    MOV BH,0
    MOV BL,FONDO
    PUSH CX
    MOV CX,1
    INT 10H
    POP CX
    INC SI
    LOOP QUITA_SNAKE
    
    
    POP CX
    RET

    BORRA_SNAKE ENDP



    END MAIN
   
    
    ;TAREA
    ;COMO HACER UN NUMERO ALEATORIO
    ;DESPLEGAR UNA COLUMNA Y RENGLON ALEATORIO PARA LAS MANZANAS
    
    
    
    
    
    
    