TITLE SNAKE JUEGO DEL SNAKE 
.MODEL SMALL
.STACK 100H
.DATA
    BORDE DB 01110111B ; CIAN FONDO CHAR MAGENTA
    FONDO DB 00000000B ; CAFE EL AREA DE JUEGO
    SNAKE_COLOR DB 00100010B ;COLOR DE SNAKE
    
    SNAKE_COL DB 20 DUP(40)
    SNAKE_REN DB 22,19 DUP(11)
    SNAKE_CHAR DB 'S'
    SNAKE_LARGO DW 5
    INC_COL DB 0
    INC_REN DB 0
    DIRECCION_SNAKE DB 1 ;1 UP, 2 DOWN, 3 LEFT, 4 RIGHT
    
    ; Colocar en el centro del campo de juego
    CENTRO_COL DB 40
    CENTRO_REN DB 11
    
    
    MANZANA_COLOR DB 01000100B ; COLOR DE LA MANZANA
    MANZANA_CHAR DB 'M'
    MANZANA_REN DB 10
    MANZANA_COL DB 10

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    ; CAMBIAR EL MODO DE VIDEO
    MOV AH,0
    MOV AL,3
    INT 10H
    
    ; PONER PAGINA ACTIVA LA 0
    MOV AH,5
    MOV AL,0
    INT 10H
    
    CALL HACER_FIELD
    
    ; Establecer posici?n inicial de la serpiente en el centro
    MOV SI, 0 ; Indice de la serpiente
    MOV AL, CENTRO_COL
    MOV SNAKE_COL[SI], AL
    MOV AL, CENTRO_REN
    MOV SNAKE_REN[SI], AL
    
    ; GENERAR Y MOSTRAR LAS MANZANAS
    CALL MANZANAS
    
    MOV CX,500
    
CICLO_PRINCIPAL:
    CALL DESPLIEGA_SNAKE
    CALL ESPERA
    CALL BORRA_SNAKE
    MOV AH,11H ;VERIFICAR CHAR
    INT 16H
    JZ NEXT ;NO HAY CHAR
    
SI_HAY_CHAR:
    MOV AH,10H
    INT 16H ;LEER CHAR
    CALL CAMBIA_DIRECCION

NEXT:
    CALL AVANZA_SNAKE
    LOOP CICLO_PRINCIPAL
    
    ; ESPERANDO CHAR
    MOV AH,1
    INT 21H

    MOV AH, 4CH
    INT 21H
MAIN ENDP
 
HACER_FIELD PROC
    PUSH CX
    ; HACER EL BORDE EXTERIOR, LIMPIANDO LA PANTALLA
    
    MOV AH, 6
    MOV AL, 25 
    MOV CX, 0000H ; RENGLON CERO , COL 0
    MOV DX, 184FH ; RENGOL 18H, COL 4EH
    MOV BH, BORDE
    INT 10H 
    
    MOV AH,7
    MOV AL,0
    MOV CX,0101H
    MOV DX,174EH
    MOV BH,FONDO
    INT 10H
    POP CX
    
    RET
    
HACER_FIELD ENDP
DESPLIEGA_SNAKE PROC
    PUSH CX
    MOV CX, SNAKE_LARGO
    XOR SI, SI
    
MUESTRA_SNAKE:
    ; CAMBIAR A POSICION DE COL Y REN DE LA SNAKE
    MOV AH,2
    MOV DL,SNAKE_COL[SI]
    MOV DH,SNAKE_REN[SI]
    MOV BH,0
    INT 10H
    
    ; DESPLEGAR EL CHAR DEL SNAKE
    MOV AH,9
    MOV AL, SNAKE_CHAR
    MOV BH,0
    MOV BL,SNAKE_COLOR ;FONDO
    PUSH CX
    MOV CX,1
    INT 10H
    
    POP CX
    INC SI
    LOOP MUESTRA_SNAKE

    POP CX
    RET
 
DESPLIEGA_SNAKE ENDP
 
ESPERA PROC
    PUSH CX
    MOV CX, 0FFFFH
    
CICLO_ESPERA:
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    LOOP CICLO_ESPERA
    
    POP CX
    RET
    
ESPERA ENDP
 
AVANZA_SNAKE PROC
    PUSH CX
    MOV CX, SNAKE_LARGO
    MOV SI, SNAKE_LARGO
    DEC SI
    DEC CX
    DEC SI
    ;COPIAR TODOS LOS CHARS ANTERIORES DE LA SNAKE HACIA ATRAS
CICLO_AVANZA:
    MOV AL,SNAKE_REN[SI]
    MOV SNAKE_REN[SI+1], AL
    MOV AL,SNAKE_COL[SI]
    MOV SNAKE_COL[SI+1],AL
    DEC SI
    LOOP CICLO_AVANZA
    ; AVANZAR SNAKE EN LA DIRECCION CORRESPONDIENTE
    MOV AL,INC_REN
    ADD SNAKE_REN,AL
    MOV AL,INC_COL
    ADD SNAKE_COL,AL
    
    POP CX
    RET
    
AVANZA_SNAKE ENDP
 
BORRA_SNAKE PROC
    PUSH CX
    MOV CX, SNAKE_LARGO
    XOR SI, SI
    
QUITA_SNAKE:
    ; CAMBIAR A POSICION DE COL Y REN DE LA SNAKE
    MOV AH,2
    MOV DL,SNAKE_COL[SI]
    MOV DH,SNAKE_REN[SI]
    MOV BH,0
    INT 10H
    ; DESPLEGAR EL CHAR DEL SNAKE
    MOV AH,9
    MOV AL, " "
    MOV BH,0
    MOV BL,FONDO
    PUSH CX
    MOV CX,1
    INT 10H
    POP CX
    INC SI
    LOOP QUITA_SNAKE

    POP CX
    RET
 
BORRA_SNAKE ENDP
CAMBIA_DIRECCION PROC
    CMP AH,50H
    JE DOWN
    CMP AH,48H
    JE UP
    CMP AH,4BH
    JE LEFT
    CMP AH,4DH
    JE RIGHT
    JMP FIN
DOWN:
    MOV DIRECCION_SNAKE,2
    MOV INC_COL,0
    MOV INC_REN,1
    JMP FIN
UP:
    MOV DIRECCION_SNAKE,1
    MOV INC_COL,0
    MOV INC_REN,-1
    JMP FIN
LEFT:
    MOV DIRECCION_SNAKE,3
    MOV INC_COL,-1
    MOV INC_REN,0
    JMP FIN
RIGHT:
    MOV DIRECCION_SNAKE,4
    MOV INC_COL,1
    MOV INC_REN,0
FIN:
    RET    
CAMBIA_DIRECCION ENDP
 
MANZANAS PROC
    PUSH CX
    MOV CX,10
    
MOSTRAR_MANZANA:
    ; GENERAR NUMERO ALEATORIO
    ; Obtener la hora del sistema
    MOV AH, 2Ch  
    INT 21h     
    
    MOV CL, DH   ; Mueve los segundos a CL
    
    ; Inicializar el generador de n?meros aleatorios con la semilla
    MOV BX, 19585
    MOV AX, 0
    MOV AL, CL
    MUL BX
    ADD AX, 12345
    MOV CX, AX

    ; Generar una coordenada aleatoria para la columna (entre 1 y 80)
    MOV BL, 80
    XOR DX, DX
    MOV AX, CX
    DIV BL
    INC AL
    MOV MANZANA_COL, AL

    ; Generar una coordenada aleatoria para la fila (entre 1 y 25)
    MOV BL, 25
    XOR DX, DX
    MOV AX, CX
    DIV BL
    INC AL
    MOV MANZANA_REN, AL
    
    
    
    
    

    ; CAMBIAR LA POSICION DEL CURSOR
    MOV AH,2
    MOV DL,MANZANA_COL
    MOV DH,MANZANA_REN
    MOV BH,0
    INT 10H
    
    ; DESPLEGAR EL CHAR DEL SNAKE
    MOV AH,9
    MOV AL, MANZANA_CHAR
    MOV BH,0
    MOV BL,MANZANA_COLOR ;FONDO
    PUSH CX
    MOV CX,1
    INT 10H
    
    POP CX
    LOOP MOSTRAR_MANZANA 

    POP CX
    RET
   
    
MANZANAS ENDP
    END MAIN

    ;TAREA
    ;COMO HACER UN NUMERO ALEATORIO
    ;DESPLEGAR UNA COLUMNA Y RENGLON ALEATORIO PARA LAS MANZANAS